title: 'Staccato'
description: 'Staccato는 참가자들끼리 자유롭게 네트워킹하며 할 일을 할 수 있는 행사입니다. 동시에 Azure, AWS, 아키텍처, iOS, Android 개발, 딥러닝, CI, 게임 기획 및 개발, 디자인 등 12개의 주제로 깊게 이야기할 수 있는 세션도 함께 마련되어 있습니다. 개인 프로젝트를 하거나, 다양한 주제로 다른 참가자들과 이야기를 나눠보세요.'
logo: '/images/logo.svg'
logo_image: '/images/logo_image.jpg'
baseurl: '/staccato'
url: 'https://stac.github.io'
onoffmix: 'http://onoffmix.com/event/83852'
exclude:
  - scripts
  - venv
  - vendor
collections:
  - sections
